const DAILY_VERSE_READ_POLL_TYPE = 'DAILY_VERSE_READ_POLL_TYPE';
const DAILY_VERSE_READ_QUESTION = "Did you read today's verse?";
const DAILY_VERSE_READ_OPTIONS = ['Yes', 'No'];
const DAILY_VERSE_TIME_POLL_TYPE = 'DAILY_VERSE_TIME_POLL_TYPE';
const DAILY_VERSE_TIME_QUESTION = 'How long did you read?';
const DAILY_VERSE_TIME_OPTIONS = ['10m-20m', '20m-1h', '1h-2h', '> 2h'];
const HELP_MESSAGE = 'Help Message';

module.exports = {
  DAILY_VERSE_READ_POLL_TYPE,
  DAILY_VERSE_READ_QUESTION,
  DAILY_VERSE_READ_OPTIONS,
  DAILY_VERSE_TIME_POLL_TYPE,
  DAILY_VERSE_TIME_QUESTION,
  DAILY_VERSE_TIME_OPTIONS,
  HELP_MESSAGE,
};
